In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)


[10 20 30 40]


In [ ]:
# two dimensional array
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2 = np.array([[1,2],[4,5],[6,7]])
print(arr)

[[1 2]
 [4 5]
 [6 7]]


In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.size)

2
(3, 2)
int64
6


In [ ]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [ ]:
arr3=np.zeros((3,4))

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

VECTORIZED COMPUTATION

In [ ]:
number = [1,2,3,5]
result=[]
for x in number:
  result.append(x*2)
  print(result)

[2]
[2, 4]
[2, 4, 6]
[2, 4, 6, 10]


In [ ]:
arr = np.array([1,2,3,5])
result= arr*2
print(result)

[ 2  4  6 10]


In [ ]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.square(arr))
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[  1  16  81 256]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


BINARY UNIVERSAL FUNCTION

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.maximum(a,b))
print(np.minimum(a,b))


[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[1 2 3 4]
[1 2 3 4]


ARRAY OPRATION

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[  1  32 729]


In [ ]:
marks = np.array([45,70,85,30,90])
passed = marks[marks >= 40]
print(passed)


[45 70 85 90]


AGGRIGATION OPERATION

In [ ]:
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


150
10
50
30.0
30.0
14.142135623730951
200.0


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))
print(np.min(arr,axis=0))
print(np.min(arr,axis=1))

[5 7 9]
[ 6 15]
[1 2 3]
[1 4]


RESHAPING,FLATTERING AND TRANSPOSE

In [ ]:
arr = np.arange(1,13)
new_arr = arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [ ]:
# Transpose
arr = np.array([[1,2,5],[3,4,6]])
print(arr.T)

[[1 3]
 [2 4]
 [5 6]]


BROADCASTING

In [ ]:
arr = np.array([[1,2,5],[3,4,6]])
print(arr+10)

[[11 12 15]
 [13 14 16]]


In [ ]:
import numpy as np
marks = np.array([65,75,80,90,55])
print('Avrage:',np.mean(marks))
print('Maxima:',np.max(marks))
print('Minima:',np.min(marks))
print('Standard Deviation:',np.std(marks))
new_marks = marks + 5


Avrage: 73.0
Maxima: 90
Minima: 55
Standard Deviation: 12.083045973594572
